language: php
php:
  - 5.5
  - 5.4
before_script:
  - composer install
  - composer require predis/predis
script: phpunit --testdox --exclude-group=temporarilydisabled
services:
  - memcached
  - redis-server
