language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
before_script:
  - phpenv config-add .travis.php.ini
  - composer install
  - composer require predis/predis
script: phpunit --testdox
services:
  - memcached
  - redis-server
